export enum StatusDevolucao {
  AGUARDANDO_LIBERACAO = 'AGUARDANDO_LIBERACAO',
  AGUARDANDO_CONFERENCIA = 'AGUARDANDO_CONFERENCIA',
  EM_CONFERENCIA = 'EM_CONFERENCIA',
  CONFERENCIA_FINALIZADA = 'CONFERENCIA_FINALIZADA',
  FINALIZADO = 'FINALIZADO',
  CANCELADO = 'CANCELADO',
}
